### ISSUE TITLE
[LocalVariableName/ParameterName] Naming convention

### ISSUE THREAD

**Issue by JoaoASousa** [Telmooo/jpass#13]
**Describe the (bug) warning**
In `jpass.util.SpringUtilities`, there are 4 local variables and 4 parameters whose name does not match the pattern `'^[a-z]([a-z0-9][a-zA-Z0-9]*)?$'`. An example for each is `yPadSpring` and `xPad`.

**Expected behaviour**
Does not affect the execution of the application. Behaves normally.

**Desktop (please complete the following information):**
 - Version: JPass 0.1.21-SNAPSHOT

**Comment by Telmooo** [comment]
Error appears due to first part of the variable only having a single lowercase letter. I think it's fine to allow, as it still follows the camel case standard.

Personally, would change the regex to allow it.

**Comment by JoaoASousa** [comment]
After discussing it with the teacher, I'll change the names in order to conform to the convention default of Checkstyle.
