### ISSUE TITLE
[JavadocTagContinuationIndentation] Line continuation has incorrect indentation level

### ISSUE THREAD

**Issue by JoaoASousa** [Telmooo/jpass#14]
**Describe the bug**
Javadoc line continuation indentation was expected to be at level 4 but there was no indent.

Files affected:
- `jpass.crypt.Aes256` (2 occurrences; line 208, 224)
- `jpass.crypt.io.CryptOutputStream` (1 occurrence; line 116)
- `jpass.ui.EntryDialog` (1 occurrence; line 282)
- `jpass.ui.GeneratePasswordDialog` (1 occurrence; line 126)

**Expected behaviour**
Does not affect the execution of the application. Behaves normally.

**Desktop (please complete the following information):**
 - Version: JPass 0.1.21-SNAPSHOT

**Comment by Telmooo** [comment]
Looks fair to follow that recommended style, provides better readability for what `@param` each line belongs to.
