### ISSUE TITLE
[VA_FORMAT_STRING_USES_NEWLINE] Using system-specific newline instead of portable newline

### ISSUE THREAD

**Issue by Telmooo** [Telmooo/jpass#4]
**Describe the bug**
Minor bug affecting multiple properties.
Newline character `\n` always generates the byte code `U+000A`, however, this newline character may differ from system to system (`\n` used on Unix systems).
It is preferred to use the portable newline `%n` that will produce the correct newline character depending on the system where it is being executed.

Files affected:
- `jpass.ui.helper.FileHelper` (6 occurrences)

**Desktop (please complete the following information):**
 - Version: JPass 0.1.21-SNAPSHOT

**Comment by jose** [comment]
Out of curiosity, why should one use `%n` and not [`System.lineSeparator()`](https://docs.oracle.com/javase/9/docs/api/java/lang/System.html#lineSeparator--)?  Or is it the same?

**Comment by Telmooo** [comment]
From the documentation of format strings for Java, [here](https://docs.oracle.com/javase/1.5.0/docs/api/java/util/Formatter.html#dls), the line separator format character `%n` produces the line separator returned by [`System.getProperty("line.separator")`](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/System.html#getProperty(java.lang.String)).

And, as specified in the documentation for [`System.lineSeparator()`](https://docs.oracle.com/javase/9/docs/api/java/lang/System.html#lineSeparator--), this method also uses the property defined by the system property `line.separator`.
> It always returns the same value - the initial value of the [system property](https://docs.oracle.com/javase/9/docs/api/java/lang/System.html#getProperty-java.lang.String-) line.separator.

So, in practice they yield the same results. Java documentation recommends using `%n` on format strings.
